/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package clikt_debug_test_case

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands

class Cmd : CliktCommand() {
    override fun run() {
        echo("Cmd.run")
    }
}

class Sub1 : CliktCommand(help = "Subcommand 1") {
    override fun run() {
        echo("Sub1 line 1")
        echo("Sub1 line 2")
        echo("Sub1 line 3")
        echo("Sub1 line 4")
    } 
}

class Sub2 : CliktCommand(help = "Subcommand 2") {
    override fun run() = echo("subcommand 2")
}

fun main(args: Array<String>) {
    println("main")
    Cmd().subcommands(Sub1(), Sub2()).main(args)
} 